CREATE TABLE guestbook (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  homepage VARCHAR(255),
  text TEXT NOT NULL,
  ip_address VARCHAR(45) NOT NULL,
  browser VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);